### ISSUE TITLE
410 gone exception unable to read transaction data

### ISSUE THREAD

**Issue by DevGoslinga** [Evidos/SignhostClientLibrary#45]
The transaction even though available in the web user interface and signed can't be read because of the thrown 410 exception.

The SignhostClient should handle the 410 httpclient  exception and read the response body so that a transaction class instance can be returned.

**Comment by MrJoe** [comment]
It already does, the transaction data is available as a property in the exception: https://github.com/Evidos/SignhostClientLibrary/blob/master/src/SignhostAPIClient/Rest/ErrorHandling/GoneException.cs#L61
As mentioned in the comment, your transaction data is most likely incomplete after a 410 because data is thrown away by the system. That is why we don't return it as a normal transaction object.
